export const siteConfig = {
  name: 'pixel boba',
  description:
    'Fort Lauderdale web design company creating custom websites that convert visitors into customers. Local South Florida team specializing in Next.js, React, and modern web development.',
  tagline: 'websites that pop',
  url: 'https://pixelboba.com',
  ogImage: 'https://pixelboba.com/og.jpg',
  keywords: [
    'fort lauderdale web design',
    'south florida web development',
    'broward county web design',
    'miami web development',
    'palm beach web design',
    'custom website design',
    'professional web development',
    'next.js development',
    'react web development',
    'saas website design',
    'ecommerce development',
    'responsive web design',
    'conversion optimization',
    'seo web design',
    'local web design company',
    'florida web developers',
    'website redesign services',
    'modern web design',
    'user experience design',
    'mobile-first design',
  ],
  links: {
    twitter: 'https://twitter.com/pixelboba_',
    github: 'https://github.com/creamytech/pixelboba',
    instagram: 'https://instagram.com/pixel.boba',
  },
};
